from collections.abc import Sequence

class MinHash:
    def __init__(self, signature_size: int, seed: int): ...
    def update(self, data: bytes) -> None: ...
    def update_batch(self, data: Sequence[bytes]) -> None: ...
    def jaccard(self, other: MinHash) -> float: ...
    @property
    def signature(self) -> list[int]: ...
